### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by totototateyama** [totototateyama/furima-41462#20]
# URL
https://furima-41462.onrender.com/

**Comment by motomuun** [comment]
@totototateyama さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品出品機能の確認**

- [x] **発送元の地域は、「---」と47都道府県の合計48項目が表示されること（--- は初期値として設定すること）**
北海道以外の「都府県」が表示されていません。例えば「青森県」が「青森」になっています。
「都府県」が表示されるように修正をお願いします。

**商品購入機能の確認**

- [x] **クレジットカード情報は必須であり、右記のPAY.JPテストカードの情報で決済ができること**
クレジットカードの情報を入力するフォームに、情報を入力できません。入力できるように修正をお願いします。

※売却済み商品の機能に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by totototateyama** [comment]
ご確認ありがとうございました！
ご指摘の箇所を修正しましたので、再度ご確認のほど宜しくお願い致します。

【「都府県」が表示されるように修正】
https://gyazo.com/1a64bb0d69a3e7e9c4ecc1aedfd246b0

【クレジットカードの情報を入力するフォーム】
https://gyazo.com/69682c4919f0b4c1b8ad5ebd4d7cc39a

**Comment by OhyaYouki** [comment]
@totototateyama さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
